# Generated by Django 3.2.13 on 2022-05-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('sqft_living', models.FloatField()),
                ('sqft_lot', models.FloatField()),
                ('floors', models.FloatField()),
                ('waterfront', models.BooleanField()),
                ('view', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('sqft_above', models.FloatField()),
                ('sqft_basement', models.FloatField()),
                ('yr_built', models.IntegerField()),
                ('yr_renovated', models.IntegerField()),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('statezip', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'house_data',
            },
        ),
    ]
